# Site settings
title: tuongmai.com
SEOTitle: Phường Tương Mai | Hà Nội
header-img: img/ha-noi-sunset.jpg
email: tuongmai.com@gmail.com
description: "Tương Mai, Minh Khai, Trương Định, Đồng Tâm, Vĩnh Hưng, Mai Động, Tân Mai, Hoàng Văn Thụ, Giáp Bát, Phương Liệt"
keyword: "Tương Mai, Minh Khai, Trương Định, Đồng Tâm, Vĩnh Hưng, Mai Động, Tân Mai, Hoàng Văn Thụ, Giáp Bát, Phương Liệt"
url: "https://www.tuongmai.com"              # your host, for absolute URL
baseurl: "/"                            # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false

#twitter_username:  huxpro
#facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Analytics settings
# Google Analytics
ga_track_id: 'G-49LLEEJL0D'            # Format: UA-xxxxxx-xx
ga_domain: tuongmai.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Trang thông tin phường Tương Mai - TP Hà Nội"
sidebar-avatar: /img/hanoi.svg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value